[package]
name = "yandex-music-discord-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-rich-presence = "0.2.4"
dotenv_codegen = "0.15.0"
image = "0.25.1"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
tray-icon = "0.14.3"
win-gsmtc = "0.1.0"
winit = "0.30.3"
