name: dotnet package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Build
        run: dotnet publish -c Release -r win-x86 -p:PublishSingleFile=true --self-contained false
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: 
            YandexMusicDiscordRPC\bin\Release\net6.0-windows10.0.17763.0\win-x86\publish\YandexMusicDiscordRPC.exe
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: "1.0"
  
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: "YandexMusicDiscordRPC\\bin\\Release\\net6.0-windows10.0.17763.0\\win-x86\\publish\\YandexMusicDiscordRPC.exe"
          asset_name: YandexMusicDiscordRPC.exe
          asset_content_type: application/octet-stream
